// Business catalog for the claim flow.
//
// The list of businesses is build output (`/data/claim-index.json`, generated by
// src/pages/data/claim-index.json.ts), not a database table: it is always exactly
// what the deployed site shows, and it needs no seeding step or refresh job. We read
// it once per isolate and cache it in module scope for a few minutes.
//
// Why it matters: the claim endpoints resolve the business **from this catalog**, so
// a caller can only ever claim a real, listed business — and the name/category that
// end up in the registry come from the build, never from the request body.

import { RegistryError } from './registry';

export interface CatalogEntry {
  placeId: string;
  slug: string;
  name: string;
  category: string;
  address?: string;
  neighborhood?: string;
}

const INDEX_PATH = '/data/claim-index.json';
const CACHE_TTL_MS = 5 * 60_000;
const FETCH_TIMEOUT_MS = 8_000;
const PLACE_ID_SHAPE = /^[A-Za-z0-9_-]{5,300}$/;

interface CatalogCache {
  origin: string;
  fetchedAt: number;
  entries: Map<string, CatalogEntry>;
}

let cache: CatalogCache | null = null;

function isEntry(value: unknown): value is CatalogEntry {
  const entry = value as CatalogEntry | null;
  return Boolean(
    entry &&
      typeof entry.placeId === 'string' &&
      entry.placeId &&
      typeof entry.slug === 'string' &&
      typeof entry.name === 'string',
  );
}

async function fetchCatalog(origin: string): Promise<Map<string, CatalogEntry>> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const response = await fetch(`${origin}${INDEX_PATH}`, {
      signal: controller.signal,
      headers: { accept: 'application/json' },
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const body = (await response.json()) as { businesses?: unknown };
    const list = Array.isArray(body?.businesses) ? body.businesses : [];
    const entries = new Map<string, CatalogEntry>();
    for (const item of list) {
      if (isEntry(item)) entries.set(item.placeId, item);
    }
    if (!entries.size) throw new Error('catalog is empty');
    return entries;
  } finally {
    clearTimeout(timer);
  }
}

/** The business catalog for this deployment, keyed by Google Places ID. */
export async function loadCatalog(request: Request): Promise<Map<string, CatalogEntry>> {
  const origin = new URL(request.url).origin;
  if (cache && cache.origin === origin && Date.now() - cache.fetchedAt < CACHE_TTL_MS) {
    return cache.entries;
  }
  let entries: Map<string, CatalogEntry>;
  try {
    entries = await fetchCatalog(origin);
  } catch (error) {
    console.error('claim: could not load the business catalog', (error as Error).message);
    if (cache && cache.origin === origin) {
      // A stale catalog beats no catalog: the businesses do not move.
      return cache.entries;
    }
    throw new RegistryError(
      'catalog_unavailable',
      'the business list is temporarily unavailable — please try again in a minute',
      503,
    );
  }
  cache = { origin, fetchedAt: Date.now(), entries };
  return entries;
}

/** Resolve one business, or throw `not_found` / `catalog_unavailable`. */
export async function requireBusiness(request: Request, placeId: unknown): Promise<CatalogEntry> {
  const id = typeof placeId === 'string' ? placeId.trim() : '';
  if (!id || !PLACE_ID_SHAPE.test(id)) {
    throw new RegistryError('not_found', 'unknown business', 404);
  }
  const catalog = await loadCatalog(request);
  const entry = catalog.get(id);
  if (!entry) {
    throw new RegistryError('not_found', `no listed business with place id ${id}`, 404);
  }
  return entry;
}
