#!/usr/bin/env python3
"""Hobby-scale SMS OTP cost scenarios for Barcelona Compare.

Reproduces every money table in section 3 of
`docs/sms-otp-provider-cost-spike.md` (accessed 2026-09-27).

Official rates used (each cited with its URL in that document):

  Twilio, Spain, outbound SMS, alphanumeric sender ID : USD 0.0875 / segment
  Twilio, failed-message processing fee              : USD 0.001 / failed message
  OVHcloud SMS, smallest prepaid pack (Spain site)   : EUR 6.00 + IVA for 118 SMS
  Spanish IVA                                        : 21 %

Run:  /usr/bin/python3 docs/sms-otp-cost-scenarios.py

Pure stdlib. No network call, no provider account, no credential: the rates are
constants transcribed from the cited pages, and the arithmetic below is the only
thing this program does.
"""

from decimal import ROUND_CEILING, ROUND_HALF_UP, Decimal

# --- scenario definition (assumptions A1-A7 in the document) ---------------
VERIFICATIONS = (10, 25, 50, 100)  # A1: 1 verification = 1 delivered SMS = 1 segment
RETRY_FACTOR = Decimal("1.3")  # A3: 1.3 messages per verification (30 % retries/resends)
FAILED_SHARE = Decimal("0.02")  # A6: 2 % of sent messages terminate as Failed

# --- provider rates --------------------------------------------------------
TWILIO_USD_PER_SEGMENT = Decimal("0.0875")
TWILIO_FAILED_FEE_USD = Decimal("0.001")
OVH_PACK_EUR = Decimal("6.00")
OVH_PACK_SMS = 118
OVH_IVA = Decimal("0.21")
OVH_EUR_PER_SMS = OVH_PACK_EUR / OVH_PACK_SMS
OVH_PACK_IVA_EUR = (OVH_PACK_EUR * (1 + OVH_IVA)).quantize(
    Decimal("0.01"), rounding=ROUND_HALF_UP
)


def q(value, places):
    """Round half up to `places` decimals."""
    return value.quantize(Decimal(1).scaleb(-places), rounding=ROUND_HALF_UP)


def money(value, places):
    return f"{q(value, places):.{places}f}"


def table(title, header, rows):
    print(f"\n### {title}\n")
    print("| " + " | ".join(header) + " |")
    print("| " + " | ".join("---" for _ in header) + " |")
    for row in rows:
        print("| " + " | ".join(str(cell) for cell in row) + " |")


def main():
    print("SMS OTP cost scenarios, hobby scale -- generated by "
          "docs/sms-otp-cost-scenarios.py")
    print(f"As of the official rates cited in docs/sms-otp-provider-cost-spike.md "
          f"(accessed 2026-09-27).")
    print(f"Constants: Twilio USD {TWILIO_USD_PER_SEGMENT}/segment to Spain, "
          f"failed-message fee USD {TWILIO_FAILED_FEE_USD}, "
          f"OVHcloud pack EUR {OVH_PACK_EUR} + IVA ({OVH_IVA}) for {OVH_PACK_SMS} SMS "
          f"= EUR {money(OVH_EUR_PER_SMS, 4)}/SMS ex-IVA, "
          f"pack price IVA incl. EUR {money(OVH_PACK_IVA_EUR, 2)}. "
          f"Retry factor {RETRY_FACTOR}, failed share {FAILED_SHARE}.")

    # per-scenario derived quantities
    scenarios = []
    for v in VERIFICATIONS:
        vd = Decimal(v)
        base_msgs = vd
        real_msgs = vd * RETRY_FACTOR
        # Decimal `//` truncates toward zero, so ceiling explicitly.
        packs_yr = int(
            (vd * 12 / OVH_PACK_SMS).to_integral_value(rounding=ROUND_CEILING)
        )
        scenarios.append(
            {
                "v": v,
                "base_msgs": base_msgs,
                "real_msgs": real_msgs,
                "packs_per_month": vd / OVH_PACK_SMS,
                "twilio_base": base_msgs * TWILIO_USD_PER_SEGMENT,
                "twilio_real": real_msgs * TWILIO_USD_PER_SEGMENT,
                "twilio_failed": real_msgs * FAILED_SHARE * TWILIO_FAILED_FEE_USD,
                "ovh_base": base_msgs * OVH_EUR_PER_SMS,
                "ovh_real": real_msgs * OVH_EUR_PER_SMS,
                "pack_months": Decimal(OVH_PACK_SMS) / vd,
                "twilio_yr": vd * 12 * TWILIO_USD_PER_SEGMENT,
                "ovh_yr": vd * 12 * OVH_EUR_PER_SMS,
                "ovh_yr_iva": vd * 12 * OVH_EUR_PER_SMS * (1 + OVH_IVA),
                "ovh_packs_yr": packs_yr,
                "ovh_cash_yr": packs_yr * OVH_PACK_IVA_EUR,
            }
        )

    table(
        "Monthly messages",
        ["verifications/month", "messages (base, A2)", "messages (realistic, A3)"],
        [(s["v"], money(s["base_msgs"], 0), money(s["real_msgs"], 1)) for s in scenarios],
    )

    table(
        "Twilio (USD, ex-tax)",
        [
            "verifications/month",
            "base msgs",
            "base USD",
            "realistic msgs",
            "realistic USD",
            f"+USD {TWILIO_FAILED_FEE_USD} failed @{FAILED_SHARE * 100:.0f} %",
        ],
        [
            (
                s["v"],
                money(s["base_msgs"], 0),
                money(s["twilio_base"], 4),
                money(s["real_msgs"], 1),
                money(s["twilio_real"], 4),
                money(s["twilio_failed"], 5),
            )
            for s in scenarios
        ],
    )

    table(
        "OVHcloud SMS (EUR, ex-IVA message cost)",
        [
            "verifications/month",
            "base msgs",
            "base EUR",
            "realistic msgs",
            "realistic EUR",
            f"months a {OVH_PACK_SMS}-SMS pack lasts (base)",
        ],
        [
            (
                s["v"],
                money(s["base_msgs"], 0),
                money(s["ovh_base"], 4),
                money(s["real_msgs"], 1),
                money(s["ovh_real"], 4),
                money(s["pack_months"], 1),
            )
            for s in scenarios
        ],
    )

    table(
        "First year, base scenario (12 months of messages, no number rental)",
        [
            "verifications/month",
            "msgs/year",
            "Twilio USD/yr (ex-tax)",
            "OVH EUR/yr (pro-rata credit cost, ex-IVA)",
            "OVH EUR/yr incl. IVA",
            f"OVH cash out yr-1 ({OVH_PACK_SMS}-SMS packs, IVA incl.)",
        ],
        [
            (
                s["v"],
                money(s["base_msgs"] * 12, 0),
                money(s["twilio_yr"], 2),
                money(s["ovh_yr"], 2),
                money(s["ovh_yr_iva"], 2),
                f"{s['ovh_packs_yr']} x {money(OVH_PACK_IVA_EUR, 2)} = "
                f"{money(s['ovh_cash_yr'], 2)}",
            )
            for s in scenarios
        ],
    )

    print("\nOVHcloud packs are prepaid lumps: the pack is consumed as messages are")
    print(f"sent, so the smallest cash out is one pack (EUR {money(OVH_PACK_IVA_EUR, 2)}, "
          f"IVA incl.) regardless of monthly volume.")


if __name__ == "__main__":
    main()
